const OptionType = Object.freeze({
    DoNoting: 1,
    BackToTitle: 6,
    ShowItems: 7,
    ShowBackToTitle: 8,
    ShowSoundVolume: 9,
    ShowItemOption: 10,
    JumpOnBed: 11,
    CheckUnderBed: 12,
    CheckUnderPillow: 13,
    UseTinStatue: 14,
    UseCoin: 15,
    UseBanana: 16,
    UseCarKey: 17,
    UseNail: 18,
    UseFrozenBanana: 19,
    UseSalt: 20,
    UseCrossBow: 21,
    UseDetergent: 22,
    UseHandMirror: 23,
    UseDVD: 24,
    UsePencil: 25,
    GetSalt: 26,
    UseDeskKey: 27,
    CheckLeftDrawer: 28,
    CheckRightDrawer: 29,
    GetPenCil: 30,
    UseShapenedPencil: 31,
    CheckInCloset: 32,
    CheckOnCloset: 33,
    ShowPinPad: 34,
    GetCrossbow: 35,
    SetTime: 36,
    Escape: 37,
    MovePig: 38,
    GetDVD: 39,
    ReadHint: 40,
    ReadHint1: 41,
    ReadHint2: 42
  });
  
  export default OptionType;